#Estágio 1 - Base
FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
RUN mkdir /app
WORKDIR /app
EXPOSE 80/tcp

#Estágio 2 - publish
FROM microsoft/dotnet:2.2-sdk AS publish
WORKDIR /app
COPY mvc1.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o dist

#Estágio 3 - final
FROM base AS final
WORKDIR /dist
COPY --from=publish /app/dist .
ENTRYPOINT ["dotnet", "mvc1.dll"] 